swagger: '2.0'
info:
  title: SPD Response Time Prediction API
  version: "0.1"
  description: An API that can predict the response time for a call to the Seattle Police Department.

paths:
  /health:
    get:
      summary: Checks the health of the service
      description: Returns the health status of the service
      operationId: project_api.health
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

  /predict:
    post:
      summary: Entrypoint to our prediction function
      operationId: project_api.predict
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
        - in: formData
          name: priority
          required: true
          description: The priority of the call (1=highest, 9=lowest)
          type: number
        - in: formData
          name: calltype
          required: true
          description: Type of call (as a number label)
          type: number
        - in: formData
          name: precinct
          required: true
          description: Precinct where the call occurred (0=E,1=N,2=S,3=SW,4=W)
          type: number
      responses:
        '200':
          description: Prediction performed successfully
        '400':
          description: Bad Request
        '500':
          description: Unable to perform the prediction
